export interface Tip {
  id: string;
  category: "memory" | "wellness" | "productivity" | "motivation";
  text: string;
}

export interface Fact {
  id: string;
  text: string;
}

export const TIPS: Tip[] = [
  { id: "t1", category: "memory", text: "Try the 'Method of Loci': visualize placing items you want to remember in rooms of your house." },
  { id: "t2", category: "memory", text: "Chunking information into smaller groups makes it easier for your brain to process and store." },
  { id: "t3", category: "wellness", text: "Taking a 10-minute walk can significantly boost your mood and creative thinking." },
  { id: "t4", category: "productivity", text: "Use the Pomodoro Technique: 25 minutes of focus followed by a 5-minute break." },
  { id: "t5", category: "motivation", text: "Small progress is still progress. Celebrate your minor wins today!" },
  { id: "t6", category: "memory", text: "Spaced repetition is key. Review new information at increasing intervals." },
  { id: "t7", category: "wellness", text: "Stay hydrated! Your brain is about 75% water and needs it to function optimally." },
  { id: "t8", category: "productivity", text: "Eat the frog: tackle your most challenging task first thing in the morning." },
  { id: "t9", category: "motivation", text: "The expert in anything was once a beginner. Keep going." },
  { id: "t10", category: "memory", text: "Mnemonic devices like acronyms can help you remember complex lists." },
  { id: "t11", category: "wellness", text: "Practice deep breathing for 2 minutes to lower cortisol levels." },
  { id: "t12", category: "productivity", text: "Clear your workspace. A cluttered desk often leads to a cluttered mind." },
  { id: "t13", category: "motivation", text: "Your only limit is the one you set in your own mind." },
  { id: "t14", category: "memory", text: "Get enough sleep. Sleep is when your brain consolidates memories from the day." },
  { id: "t15", category: "wellness", text: "Try a digital detox for an hour before bed to improve sleep quality." },
  { id: "t16", category: "productivity", text: "Batch similar tasks together to minimize context switching." },
  { id: "t17", category: "motivation", text: "Consistency beats intensity every single time." },
  { id: "t18", category: "memory", text: "Teach what you've learned to someone else. It reinforces your own understanding." },
  { id: "t19", category: "wellness", text: "Express gratitude. Writing down three things you're thankful for can improve long-term happiness." },
  { id: "t20", category: "productivity", text: "Set specific, measurable goals for your day instead of a vague to-do list." },
  { id: "t21", category: "motivation", text: "Don't compare your Chapter 1 to someone else's Chapter 20." },
  { id: "t22", category: "memory", text: "Stay mentally active. Puzzles and games like those in MemTool help keep your brain sharp." },
  { id: "t23", category: "wellness", text: "Listen to calming music or nature sounds to reduce stress levels." },
  { id: "t24", category: "productivity", text: "Turn off non-essential notifications to maintain deep focus." },
  { id: "t25", category: "motivation", text: "Action is the foundational key to all success." },
  { id: "t26", category: "memory", text: "Visual association: connect a new name or word with a vivid image." },
  { id: "t27", category: "wellness", text: "Spend some time in nature. It's proven to reduce mental fatigue." },
  { id: "t28", category: "productivity", text: "Review your day for 5 minutes each evening to prepare for tomorrow." },
  { id: "t29", category: "motivation", text: "Believe you can and you're halfway there." },
  { id: "t30", category: "memory", text: "The 'Baker-Baker Paradox': You're more likely to remember someone is a baker than their name is Mr. Baker because of the mental associations." },
  { id: "t31", category: "wellness", text: "A 20-minute power nap can improve alertness and mood." },
  { id: "t32", category: "productivity", text: "Use 'Time Boxing' to allocate specific periods to certain tasks." },
  { id: "t33", category: "motivation", text: "Success is the sum of small efforts, repeated day-in and day-out." },
  { id: "t34", category: "memory", text: "Try writing things down by hand. It often leads to better retention than typing." },
  { id: "t35", category: "wellness", text: "Practice mindfulness meditation to improve focus and emotional regulation." },
  { id: "t36", category: "productivity", text: "Avoid multitasking. It actually reduces productivity by up to 40%." },
  { id: "t37", category: "motivation", text: "The future depends on what you do today." },
  { id: "t38", category: "memory", text: "Expose yourself to new experiences. Novelty stimulates the brain's reward system and memory." },
  { id: "t39", category: "wellness", text: "Laugh more! Laughter reduces stress hormones and triggers endorphins." },
  { id: "t40", category: "productivity", text: "Keep your meetings short and focused. Always have a clear agenda." },
  { id: "t41", category: "motivation", text: "Hardships often prepare ordinary people for an extraordinary destiny." },
  { id: "t42", category: "memory", text: "Use all your senses. The more senses involved in learning, the better the memory." },
  { id: "t43", category: "wellness", text: "Eat brain-healthy foods like berries, nuts, and fatty fish." },
  { id: "t44", category: "productivity", text: "Delegate tasks that others can do, so you can focus on your unique strengths." },
  { id: "t45", category: "motivation", text: "It does not matter how slowly you go as long as you do not stop." },
  { id: "t46", category: "memory", text: "Active recall: test yourself instead of just re-reading information." },
  { id: "t47", category: "wellness", text: "Limit your caffeine intake in the afternoon to protect your sleep." },
  { id: "t48", category: "productivity", text: "Identify your most productive hours and schedule your deep work then." },
  { id: "t49", category: "motivation", text: "The only way to do great work is to love what you do." },
  { id: "t50", category: "memory", text: "Rhymes and songs can be incredibly powerful tools for memorization." },
  { id: "t51", category: "wellness", text: "Take regular breaks to stretch and move your body during the day." },
  { id: "t52", category: "productivity", text: "Set a 'Done' list, not just a 'To-Do' list, to see your progress." },
  { id: "t53", category: "motivation", text: "Every day is a second chance." },
  { id: "t54", category: "memory", text: "Context matters. Try to study or learn in an environment similar to where you'll use the info." },
  { id: "t55", category: "wellness", text: "Maintain social connections. Talking to friends is great for cognitive health." },
  { id: "t56", category: "productivity", text: "Use a planner or digital calendar to offload the mental burden of scheduling." },
  { id: "t57", category: "motivation", text: "Dreams don't work unless you do." },
  { id: "t58", category: "memory", text: "Stay curious. A curious mind is a learning mind." },
  { id: "t59", category: "wellness", text: "Practice self-compassion. Be as kind to yourself as you would be to a friend." },
  { id: "t60", category: "productivity", text: "Say 'no' to things that don't align with your priorities." },
];

export const FACTS: Fact[] = [
  { id: "f1", text: "Your brain's storage capacity is considered virtually unlimited." },
  { id: "f2", text: "The brain is the only organ that doesn't have pain receptors." },
  { id: "f3", text: "Information travels at different speeds within different types of neurons." },
  { id: "f4", text: "Your brain generates about 20 watts of electrical power while awake." },
  { id: "f5", text: "The human brain has about 86 billion neurons." },
  { id: "f6", text: "A piece of brain tissue the size of a grain of sand contains 100,000 neurons." },
  { id: "f7", text: "The brain is about 60% fat, making it the fattiest organ in the body." },
  { id: "f8", text: "Your brain uses 20% of your body's total oxygen and energy." },
  { id: "f9", text: "The hippocampus, crucial for memory, can grow new neurons throughout life." },
  { id: "f10", text: "Short-term memory lasts only about 20 to 30 seconds." },
  { id: "f11", text: "Memories are not stored in just one part of the brain; they're distributed." },
  { id: "f12", text: "Forgetfulness can actually be a sign of a high-functioning memory system." },
  { id: "f13", text: "Multi-tasking doesn't exist for the brain; it just switches tasks rapidly." },
  { id: "f14", text: "Chronic stress can physically shrink parts of the brain related to memory." },
  { id: "f15", text: "Reading aloud uses different brain circuits than reading silently." },
  { id: "f16", text: "Your brain is more active when you are dreaming than when you are awake." },
  { id: "f17", text: "Learning a second language can improve cognitive function and delay dementia." },
  { id: "f18", text: "The brain's structure is constantly changing based on your experiences (neuroplasticity)." },
  { id: "f19", text: "Smell is the only sense with a direct link to the brain's emotional and memory centers." },
  { id: "f20", text: "Visual information is processed 60,000 times faster than text." },
  { id: "f21", text: "The gut is often called the 'second brain' because it has its own nervous system." },
  { id: "f22", text: "Daydreaming can occupy up to 30-50% of our waking hours." },
  { id: "f23", text: "Music can trigger intense memory recall by activating multiple brain regions." },
  { id: "f24", text: "Exercise increases blood flow to the brain and stimulates growth factors." },
  { id: "f25", text: "Your brain's development isn't complete until your mid-twenties." },
  { id: "f26", text: "The left and right hemispheres are connected by 200 million nerve fibers." },
  { id: "f27", text: "Meditation can increase gray matter density in just 8 weeks." },
  { id: "f28", text: "Dehydration of just 2% can significantly impair cognitive tasks." },
  { id: "f29", text: "Social isolation can be as harmful to the brain as physical illness." },
  { id: "f30", text: "Deep sleep helps 'wash' the brain of toxins accumulated during the day." },
];
